monolog:
    handlers:
        forged:
            type: stream
            path: '%kernel.logs_dir%/file_of_log.log'
            level: error
        main:
            type: fingers_crossed
            action_level: error
            handler: forged
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
