vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        files:
            uri_prefix: /files/upload
            upload_destination: '%kernel.project_dir%/public/upload/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true